## Problem

$$f(w_1, w_2) = 0.1w_1^2 + 2w_2^2 \;\;\;\;\;\;\;(1)$$

In [25]:
import numpy as np

### RMSprop

In [26]:
def df_w(W):
    """
    Thực hiện tính gradient của dw1 và dw2
    Arguments:
    W -- np.array [w1, w2]
    Returns:
    dW -- np.array [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    """
    #################### YOUR CODE HERE ####################


    dW = np.array([0.1 * 2 * W[0], 2 * 2 * W[1]]) 
    ########################################################

    return dW

In [27]:
def RMSProp(W, dW, lr, S, gamma):
    """
    Thực hiện thuật tóan RMSProp để update w1 và w2
    Arguments:
    W -- np.array: [w1, w2]
    dW -- np.array: [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    lr -- float: learning rate
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients
    gamma -- float: hệ số long-range average
    Returns:
    W -- np.array: [w1, w2] w1 và w2 sau khi đã update
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients sau khi đã cập nhật
    """
    epsilon = 1e-6
    #################### YOUR CODE HERE ####################

    S = gamma * S + (1 - gamma) * np.power(dW, 2)

    W = W - lr * dW / np.sqrt(S + epsilon)
    ########################################################
    return W, S

In [28]:
def train_p1(optimizer, lr, epochs):
    """
    Thực hiện tìm điểm minimum của function (1) dựa vào thuật toán
    được truyền vào từ optimizer
    Arguments:
    optimize : function thực hiện thuật toán optimization cụ thể
    lr -- float: learning rate
    epochs -- int: số lượng lần (epoch) lặp để tìm điểm minimum
    Returns:
    results -- list: list các cặp điểm [w1, w2] sau mỗi epoch (mỗi lần cập nhật)
    """
    # initial
    W = np.array([-5, -2], dtype=np.float32)
    S = np.array([0, 0], dtype=np.float32)
    results = [W]
    #################### YOUR CODE HERE ####################
    # Tạo vòng lặp theo số lần epochs
    # tìm gradient dW gồm dw1 và dw2
    # dùng thuật toán optimization cập nhật w1, w2, s1, s2
    # append cặp [w1, w2] vào list results
    for i in range(epochs):
        W, V = optimizer(W, df_w(W), lr, S, 0.9)
        results.append(W)

    ########################################################
    return results

In [29]:
train_p1(RMSProp, lr=0.3, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.05132145, -1.05131678]),
 array([-3.10264537, -0.10263375]),
 array([-2.15397439,  0.84602141]),
 array([-1.20531665, -0.10266148]),
 array([-0.25671497,  0.8459937 ]),
 array([ 0.69017403, -0.10268919]),
 array([-0.25826042,  0.845966  ]),
 array([ 0.68864993, -0.10271689]),
 array([-0.25978341,  0.84593831]),
 array([ 0.6871476 , -0.10274457]),
 array([-0.26128465,  0.84591065]),
 array([ 0.68566639, -0.10277224]),
 array([-0.26276477,  0.84588299]),
 array([ 0.68420568, -0.10279989]),
 array([-0.26422441,  0.84585535]),
 array([ 0.68276486, -0.10282753]),
 array([-0.26566416,  0.84582773]),
 array([ 0.68134337, -0.10285515]),
 array([-0.26708458,  0.84580012]),
 array([ 0.67994068, -0.10288276]),
 array([-0.26848622,  0.84577253]),
 array([ 0.67855626, -0.10291035]),
 array([-0.26986959,  0.84574495]),
 array([ 0.67718963, -0.10293793]),
 array([-0.27123519,  0.84571739]),
 array([ 0.67584031, -0.10296549]),
 array([-0.27258348,  0.84568