## Problem

$$f(w_1, w_2) = 0.1w_1^2 + 2w_2^2 \;\;\;\;\;\;\;(1)$$

In [1]:
import numpy as np

### RMSprop

In [2]:
def df_w(W):
    """
    Thực hiện tính gradient của dw1 và dw2
    Arguments:
    W -- np.array [w1, w2]
    Returns:
    dW -- np.array [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    """
    #################### YOUR CODE HERE ####################


    dW = np.array([0.1 * 2 * W[0], 2 * 2 * W[1]]) 
    ########################################################

    return dW

In [3]:
def RMSProp(W, dW, lr, S, gamma):
    """
    Thực hiện thuật tóan RMSProp để update w1 và w2
    Arguments:
    W -- np.array: [w1, w2]
    dW -- np.array: [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    lr -- float: learning rate
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients
    gamma -- float: hệ số long-range average
    Returns:
    W -- np.array: [w1, w2] w1 và w2 sau khi đã update
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients sau khi đã cập nhật
    """
    epsilon = 1e-6
    #################### YOUR CODE HERE ####################

    S = gamma * S + (1 - gamma) * dW**2

    W = W - lr * dW / np.sqrt(S + epsilon)
    ########################################################
    return W, S

In [18]:
def train_p1(optimizer, lr, epochs):
    """
    Thực hiện tìm điểm minimum của function (1) dựa vào thuật toán
    được truyền vào từ optimizer
    Arguments:
    optimize : function thực hiện thuật toán optimization cụ thể
    lr -- float: learning rate
    epochs -- int: số lượng lần (epoch) lặp để tìm điểm minimum
    Returns:
    results -- list: list các cặp điểm [w1, w2] sau mỗi epoch (mỗi lần cập nhật)
    """
    # initial
    W = np.array([-5, -2], dtype=np.float32)
    S = np.array([0, 0], dtype=np.float32)
    results = [W]
    #################### YOUR CODE HERE ####################
    # Tạo vòng lặp theo số lần epochs
    # tìm gradient dW gồm dw1 và dw2
    # dùng thuật toán optimization cập nhật w1, w2, s1, s2
    # append cặp [w1, w2] vào list results
    for i in range(epochs):
        W, V = optimizer(W, df_w(W), lr, S, 0.1)
        results.append(W)

    ########################################################
    return results

In [19]:
train_p1(RMSProp, lr=0.3, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.68377241, -1.68377224]),
 array([-4.36754484, -1.36754447]),
 array([-4.05131731, -1.05131671]),
 array([-3.73508981, -0.73508896]),
 array([-3.41886236, -0.41886121]),
 array([-3.10263497, -0.10263351]),
 array([-2.78640766,  0.21359321]),
 array([-2.47018046, -0.10263431]),
 array([-2.15395341,  0.21359241]),
 array([-1.83772659, -0.10263511]),
 array([-1.52150013,  0.21359161]),
 array([-1.20527426, -0.10263591]),
 array([-0.88904952,  0.21359081]),
 array([-0.57282731, -0.10263672]),
 array([-0.25661292,  0.21359001]),
 array([ 0.05954817, -0.10263752]),
 array([-0.25544823,  0.21358921]),
 array([ 0.06071225, -0.10263832]),
 array([-0.25433065,  0.2135884 ]),
 array([ 0.06182923, -0.10263912]),
 array([-0.25325586,  0.2135876 ]),
 array([ 0.06290345, -0.10263992]),
 array([-0.25222014,  0.2135868 ]),
 array([ 0.06393861, -0.10264072]),
 array([-0.25122026,  0.213586  ]),
 array([ 0.06493794, -0.10264153]),
 array([-0.25025342,  0.21358