## Problem

$$f(w_1, w_2) = 0.1w_1^2 + 2w_2^2 \;\;\;\;\;\;\;(1)$$

In [23]:
import numpy as np
from scipy.linalg import sqrtm

### Adam

In [24]:
def df_w(W):
    """
    Thực hiện tính gradient của dw1 và dw2
    Arguments:
    W -- np.array [w1, w2]
    Returns:
    dW -- np.array [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    """
    #################### YOUR CODE HERE ####################


    dW = np.array([0.1 * 2 * W[0], 2 * 2 * W[1]]) 
    ########################################################

    return dW

In [25]:
def Adam(W, dW, lr, V, S, beta1, beta2, t):
    """
    Thực hiện thuật tóan Adam để update w1 và w2
    Arguments:
    W -- np.array: [w1, w2]
    dW -- np.array: [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    lr -- float: learning rate
    V -- np.array: [v1, v2] Exponentially weighted averages gradients
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients
    beta1 -- float: hệ số long-range average cho V
    beta2 -- float: hệ số long-range average cho S
    t -- int: lần thứ t update (bắt đầu bằng 1)
    Returns:
    W -- np.array: [w1, w2] w1 và w2 sau khi đã update
    V -- np.array: [v1, v2] Exponentially weighted averages gradients sau khi đã cập nhật
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients sau khi đã cập nhật
    """
    epsilon = 1e-6
    #################### YOUR CODE HERE ####################
    V = beta1 * V + (1 - beta1) * dW
    S = beta2 * S + (1 - beta2) * dW**2
    
    # Bias correction 
    V_corr = V / (1 - beta1**t)
    S_corr = S / (1 - beta2**t)
    W = W - lr * V_corr / (np.sqrt(S_corr) + epsilon)
    ########################################################
    return W, V, S

In [26]:
def train_p1(optimizer, lr, epochs):
    """
    Thực hiện tìm điểm minimum của function (1) dựa vào thuật toán
    được truyền vào từ optimizer
    Arguments:
    optimize : function thực hiện thuật toán optimization cụ thể
    lr -- float: learning rate
    epochs -- int: số lượng lần (epoch) lặp để tìm điểm minimum
    Returns:
    results -- list: list các cặp điểm [w1, w2] sau mỗi epoch (mỗi lần cập nhật)
    """
    # initial
    W = np.array([-5, -2], dtype=np.float32)
    V = np.array([0, 0], dtype=np.float32)
    S = np.array([0, 0], dtype=np.float32)
    results = [W]
    #################### YOUR CODE HERE ####################
    # Tạo vòng lặp theo số lần epochs
    # tìm gradient dW gồm dw1 và dw2
    # dùng thuật toán optimization cập nhật w1, w2, s1, s2, v1, v2
    # append cặp [w1, w2] vào list results
    # các bạn lưu ý mỗi lần lặp nhớ lấy t (lần thứ t lặp) và t bất đầu bằng 1
    for i in range(1, epochs + 1):
        W, V, S = optimizer(W, df_w(W), lr, V, S, 0.5, 0.1, i)
        results.append(W)

    ########################################################
    return results

In [27]:
train_p1(Adam, lr=0.2, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.8000002 , -1.80000002]),
 array([-4.59800221, -1.59476931]),
 array([-4.3939846 , -1.38328769]),
 array([-4.18828855, -1.16513896]),
 array([-3.9812533 , -0.93945416]),
 array([-3.77313012, -0.70405959]),
 array([-3.56407831, -0.45367693]),
 array([-3.35417917, -0.1732399 ]),
 array([-3.14345134,  0.2069591 ]),
 array([-2.93186243,  0.31295868]),
 array([-2.71933549,  0.24639983]),
 array([-2.50574983,  0.10886097]),
 array([-2.2909359, -0.1075964]),
 array([-2.07466269, -0.13822808]),
 array([-1.85661489, -0.04877582]),
 array([-1.63635299,  0.12468409]),
 array([-1.41324252,  0.06636704]),
 array([-1.18632104, -0.07150599]),
 array([-0.95402484, -0.0424527 ]),
 array([-0.7135524 ,  0.07193538]),
 array([-0.45907637,  0.00674052]),
 array([-0.1749394 , -0.12160332]),
 array([ 0.2100285 , -0.02915919]),
 array([0.31816748, 0.15100296]),
 array([0.25232383, 0.07480872]),
 array([ 0.11537667, -0.07896558]),
 array([-0.09865604, -0.06119088]),